name: Dynamic Scheduler Examples

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        clean: false

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libfl-dev git
        sudo apt-get install gcc-10 g++-10
    - name: Build Verilator
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cd verilator
        git show
        autoconf
        ./configure
        make -j$(nproc)
        cd ..
        tar acf verilator.tar.bz2 verilator

    - name: upload built verilator
      uses: actions/upload-artifact@v2
      with:
        name: verilator-build
        path: verilator.tar.bz2

  run:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        example: [uart, clock, events, fork, pong, randomize, wait]
    name: ${{ matrix.example }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
          clean: false
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfl-dev git
          sudo apt-get install gcc-10 g++-10
      - name: remove clean verilator
        run: |
          rm -rf verilator
      - name: download verilator
        uses: actions/download-artifact@v2
        with:
          name: verilator-build
      - name: unpack
        run: |
          tar xf verilator.tar.bz2
      - name: install
        run: |
          cd verilator
          sudo make install
      - name: check installation
        run: |
          verilator --version
      - name: run example
        run: |
          make ${{ matrix.example}}
