name: Dynamic Scheduler Examples

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        example: [uart, clock,  events,  fork,  pong, wait]
    name: ${{ matrix.example }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
          clean: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfl-dev git
          sudo apt-get install gcc-10 g++-10
      - name: Build Verilator
        env:
          CC: gcc-10
          CXX: g++-10
        run: |
          cd verilator
          git show
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install
      - name: Verilator version
        run: |
          verilator --version
      - name: run example
        run: |
          make ${{ matrix.example}}
